networks:
  default:
    external: false
    name: nodejs-service-local

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "${PORT}:${PORT}"
    command: npm run start:migrate
    depends_on:
      - db
    links:
      - ${DB_HOST}

  db:
    build: 
      context: .
      dockerfile: Dockerfile-db
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./db-data:/var/lib/postgresql/data:z
    command: postgres -c 'max_connections=1000' '-c' 'logging_collector=on' '-c' 'log_statement=mod'

volumes:
  db-data: 