version: "3.7"

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db

  db:
    build: ./db/.
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"

